#!/bin/sh

# TODO:
#    Get the #!ipxe shit working. :|
tftp="./netboot"
bootloader="/bootloader.0"

sudo qemu-system-x86_64                                   \
    -cpu host                                             \
    -accel kvm                                            \
    -netdev user,id=net0,tftp=$tftp,bootfile=$bootloader, \
    -device virtio-net-pci,netdev=net0                    \
    -drive file=ipxe.dsk,format=raw,index=0,if=floppy     \
    -display gtk                                          \
    -m 4096                                               \
    -chardev pty,id=serial1                               \
    -boot an
